//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commodity
    {
        public string CommodityId { get; set; }
        public string CommodityName { get; set; }
        public int CommodityPrice { get; set; }
        public int CommodityAmount { get; set; }
        public string CommodityImage { get; set; }

        public Commodity(string commodityId, string commodityName, int commodityPrice, int commodityAmount, string commodityImage)
        {
            CommodityId = commodityId;
            CommodityName = commodityName;
            CommodityPrice = commodityPrice;
            CommodityAmount = commodityAmount;
            CommodityImage = commodityImage;
        }

        public Commodity()
        {
        }
    }
}
